/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: queries.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "queries.pb-c.h"
void   select_query__init
                     (SelectQuery         *message)
{
  static SelectQuery init_value = SELECT_QUERY__INIT;
  *message = init_value;
}
size_t select_query__get_packed_size
                     (const SelectQuery *message)
{
  assert(message->base.descriptor == &select_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t select_query__pack
                     (const SelectQuery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &select_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t select_query__pack_to_buffer
                     (const SelectQuery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &select_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SelectQuery *
       select_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SelectQuery *)
     protobuf_c_message_unpack (&select_query__descriptor,
                                allocator, len, data);
}
void   select_query__free_unpacked
                     (SelectQuery *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &select_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor select_query__field_descriptors[1] =
{
  {
    "table",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SelectQuery, table),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned select_query__field_indices_by_name[] = {
  0,   /* field[0] = table */
};
static const ProtobufCIntRange select_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor select_query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SelectQuery",
  "SelectQuery",
  "SelectQuery",
  "",
  sizeof(SelectQuery),
  1,
  select_query__field_descriptors,
  select_query__field_indices_by_name,
  1,  select_query__number_ranges,
  (ProtobufCMessageInit) select_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
