/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: queries.proto */

#ifndef PROTOBUF_C_queries_2eproto__INCLUDED
#define PROTOBUF_C_queries_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _SelectQuery SelectQuery;


/* --- enums --- */


/* --- messages --- */

struct  _SelectQuery
{
  ProtobufCMessage base;
  char *table;
};
#define SELECT_QUERY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&select_query__descriptor) \
    , NULL }


/* SelectQuery methods */
void   select_query__init
                     (SelectQuery         *message);
size_t select_query__get_packed_size
                     (const SelectQuery   *message);
size_t select_query__pack
                     (const SelectQuery   *message,
                      uint8_t             *out);
size_t select_query__pack_to_buffer
                     (const SelectQuery   *message,
                      ProtobufCBuffer     *buffer);
SelectQuery *
       select_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   select_query__free_unpacked
                     (SelectQuery *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SelectQuery_Closure)
                 (const SelectQuery *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor select_query__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_queries_2eproto__INCLUDED */
